package com.sogou.bizwork.cas.user.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sogou.bizwork.cas.user.model.PersonalInfo;
import com.sogou.bizwork.cas.user.model.User;
import com.sogou.bizwork.cas.user.model.UserExample;
import com.sogou.bizwork.cas.user.model.UserInfo;

public interface UserMapper {

    String getNameByEmployeeId(Integer employeeId);

    List<String> getNameByEmployeeIds(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    List<User> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    List<User> selectUsers();

	void updateUserInfo(@Param("userInfo") UserInfo userInfo, @Param("employeeId") Integer employeeid);

	UserInfo getUserInfo(Integer employeeid);



	User getUserByUsername(String userName);

	PersonalInfo getPersonalInfoByEmployeeId(@Param(value="employeeid") Integer employeeid);

	void updatePersonalInfoByEmployeeId(PersonalInfo personalInfo);
	

}