package com.sogou.bizwork.cas.application.dao;

import com.sogou.bizwork.cas.application.model.AppAttribute;
import com.sogou.bizwork.cas.application.model.AppAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int countByExample(AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int deleteByExample(AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer appAttributeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int insert(AppAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int insertSelective(AppAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	List<AppAttribute> selectByExample(AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	AppAttribute selectByPrimaryKey(Integer appAttributeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AppAttribute record,
			@Param("example") AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AppAttribute record,
			@Param("example") AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AppAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AppAttribute record);
}