package com.sogou.bizwork.cas.application.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class AppAttributeExample implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public AppAttributeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAppAttributeIdIsNull() {
			addCriterion("appattributeid is null");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdIsNotNull() {
			addCriterion("appattributeid is not null");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdEqualTo(Integer value) {
			addCriterion("appattributeid =", value, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdNotEqualTo(Integer value) {
			addCriterion("appattributeid <>", value, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdGreaterThan(Integer value) {
			addCriterion("appattributeid >", value, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("appattributeid >=", value, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdLessThan(Integer value) {
			addCriterion("appattributeid <", value, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdLessThanOrEqualTo(Integer value) {
			addCriterion("appattributeid <=", value, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdIn(List<Integer> values) {
			addCriterion("appattributeid in", values, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdNotIn(List<Integer> values) {
			addCriterion("appattributeid not in", values, "appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdBetween(Integer value1, Integer value2) {
			addCriterion("appattributeid between", value1, value2,
					"appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppAttributeIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("appattributeid not between", value1, value2,
					"appAttributeId");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("appid is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("appid is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(Integer value) {
			addCriterion("appid =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(Integer value) {
			addCriterion("appid <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(Integer value) {
			addCriterion("appid >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("appid >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(Integer value) {
			addCriterion("appid <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(Integer value) {
			addCriterion("appid <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<Integer> values) {
			addCriterion("appid in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<Integer> values) {
			addCriterion("appid not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(Integer value1, Integer value2) {
			addCriterion("appid between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(Integer value1, Integer value2) {
			addCriterion("appid not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIsNull() {
			addCriterion("attributeid is null");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIsNotNull() {
			addCriterion("attributeid is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeIdEqualTo(Integer value) {
			addCriterion("attributeid =", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotEqualTo(Integer value) {
			addCriterion("attributeid <>", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdGreaterThan(Integer value) {
			addCriterion("attributeid >", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("attributeid >=", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLessThan(Integer value) {
			addCriterion("attributeid <", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLessThanOrEqualTo(Integer value) {
			addCriterion("attributeid <=", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIn(List<Integer> values) {
			addCriterion("attributeid in", values, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotIn(List<Integer> values) {
			addCriterion("attributeid not in", values, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdBetween(Integer value1, Integer value2) {
			addCriterion("attributeid between", value1, value2, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("attributeid not between", value1, value2,
					"attributeId");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNull() {
			addCriterion("enabled is null");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNotNull() {
			addCriterion("enabled is not null");
			return (Criteria) this;
		}

		public Criteria andEnabledEqualTo(Integer value) {
			addCriterion("enabled =", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotEqualTo(Integer value) {
			addCriterion("enabled <>", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThan(Integer value) {
			addCriterion("enabled >", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThanOrEqualTo(Integer value) {
			addCriterion("enabled >=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThan(Integer value) {
			addCriterion("enabled <", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThanOrEqualTo(Integer value) {
			addCriterion("enabled <=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledIn(List<Integer> values) {
			addCriterion("enabled in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotIn(List<Integer> values) {
			addCriterion("enabled not in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledBetween(Integer value1, Integer value2) {
			addCriterion("enabled between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotBetween(Integer value1, Integer value2) {
			addCriterion("enabled not between", value1, value2, "enabled");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uuc_appattribute
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uuc_appattribute
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}