package com.sogou.bizwork.cas.application.model;

import java.io.Serializable;

public class AppAttribute implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 342599259451238610L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_appattribute.appattributeid
	 * @mbggenerated
	 */
	private Integer appAttributeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_appattribute.appid
	 * @mbggenerated
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_appattribute.attributeid
	 * @mbggenerated
	 */
	private Integer attributeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_appattribute.enabled
	 * @mbggenerated
	 */
	private Integer enabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_appattribute.appattributeid
	 * @return  the value of uuc_appattribute.appattributeid
	 * @mbggenerated
	 */
	public Integer getAppAttributeId() {
		return appAttributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_appattribute.appattributeid
	 * @param appAttributeId  the value for uuc_appattribute.appattributeid
	 * @mbggenerated
	 */
	public void setAppAttributeId(Integer appAttributeId) {
		this.appAttributeId = appAttributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_appattribute.appid
	 * @return  the value of uuc_appattribute.appid
	 * @mbggenerated
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_appattribute.appid
	 * @param appId  the value for uuc_appattribute.appid
	 * @mbggenerated
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_appattribute.attributeid
	 * @return  the value of uuc_appattribute.attributeid
	 * @mbggenerated
	 */
	public Integer getAttributeId() {
		return attributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_appattribute.attributeid
	 * @param attributeId  the value for uuc_appattribute.attributeid
	 * @mbggenerated
	 */
	public void setAttributeId(Integer attributeId) {
		this.attributeId = attributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_appattribute.enabled
	 * @return  the value of uuc_appattribute.enabled
	 * @mbggenerated
	 */
	public Integer getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_appattribute.enabled
	 * @param enabled  the value for uuc_appattribute.enabled
	 * @mbggenerated
	 */
	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}
}