package com.sogou.bizwork.cas.application.model;

import java.io.Serializable;
import java.util.Date;

public class Application implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -4125006498629201542L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.appid
	 * @mbggenerated
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.serviceid
	 * @mbggenerated
	 */
	private String serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.ssoenabled
	 * @mbggenerated
	 */
	private Integer ssoEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.createdate
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.changedate
	 * @mbggenerated
	 */
	private Date changeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.usersource
	 * @mbggenerated
	 */
	private Integer userSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_application.intraneturl
	 * @mbggenerated
	 */
	private String intraneturl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.appid
	 * @return  the value of uuc_application.appid
	 * @mbggenerated
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.appid
	 * @param appId  the value for uuc_application.appid
	 * @mbggenerated
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.serviceid
	 * @return  the value of uuc_application.serviceid
	 * @mbggenerated
	 */
	public String getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.serviceid
	 * @param serviceId  the value for uuc_application.serviceid
	 * @mbggenerated
	 */
	public void setServiceId(String serviceId) {
		this.serviceId = serviceId == null ? null : serviceId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.name
	 * @return  the value of uuc_application.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.name
	 * @param name  the value for uuc_application.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.ssoenabled
	 * @return  the value of uuc_application.ssoenabled
	 * @mbggenerated
	 */
	public Integer getSsoEnabled() {
		return ssoEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.ssoenabled
	 * @param ssoEnabled  the value for uuc_application.ssoenabled
	 * @mbggenerated
	 */
	public void setSsoEnabled(Integer ssoEnabled) {
		this.ssoEnabled = ssoEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.description
	 * @return  the value of uuc_application.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.description
	 * @param description  the value for uuc_application.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.createdate
	 * @return  the value of uuc_application.createdate
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.createdate
	 * @param createDate  the value for uuc_application.createdate
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.changedate
	 * @return  the value of uuc_application.changedate
	 * @mbggenerated
	 */
	public Date getChangeDate() {
		return changeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.changedate
	 * @param changeDate  the value for uuc_application.changedate
	 * @mbggenerated
	 */
	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.usersource
	 * @return  the value of uuc_application.usersource
	 * @mbggenerated
	 */
	public Integer getUserSource() {
		return userSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.usersource
	 * @param userSource  the value for uuc_application.usersource
	 * @mbggenerated
	 */
	public void setUserSource(Integer userSource) {
		this.userSource = userSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_application.intraneturl
	 * @return  the value of uuc_application.intraneturl
	 * @mbggenerated
	 */
	public String getIntraneturl() {
		return intraneturl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_application.intraneturl
	 * @param intraneturl  the value for uuc_application.intraneturl
	 * @mbggenerated
	 */
	public void setIntraneturl(String intraneturl) {
		this.intraneturl = intraneturl == null ? null : intraneturl.trim();
	}
}