package com.sogou.bizwork.cas.application.model;

import java.io.Serializable;

public class Attribute implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5146153248040221554L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_attribute.attributeid
	 * @mbggenerated
	 */
	private Integer attributeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_attribute.attributename
	 * @mbggenerated
	 */
	private String attributeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_attribute.attributevalue
	 * @mbggenerated
	 */
	private String attributeValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_attribute.attributemap
	 * @mbggenerated
	 */
	private String attributeMap;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uuc_attribute.needed
	 * @mbggenerated
	 */
	private Integer needed;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_attribute.attributeid
	 * @return  the value of uuc_attribute.attributeid
	 * @mbggenerated
	 */
	public Integer getAttributeId() {
		return attributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_attribute.attributeid
	 * @param attributeId  the value for uuc_attribute.attributeid
	 * @mbggenerated
	 */
	public void setAttributeId(Integer attributeId) {
		this.attributeId = attributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_attribute.attributename
	 * @return  the value of uuc_attribute.attributename
	 * @mbggenerated
	 */
	public String getAttributeName() {
		return attributeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_attribute.attributename
	 * @param attributeName  the value for uuc_attribute.attributename
	 * @mbggenerated
	 */
	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName == null ? null : attributeName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_attribute.attributevalue
	 * @return  the value of uuc_attribute.attributevalue
	 * @mbggenerated
	 */
	public String getAttributeValue() {
		return attributeValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_attribute.attributevalue
	 * @param attributeValue  the value for uuc_attribute.attributevalue
	 * @mbggenerated
	 */
	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue == null ? null : attributeValue
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_attribute.attributemap
	 * @return  the value of uuc_attribute.attributemap
	 * @mbggenerated
	 */
	public String getAttributeMap() {
		return attributeMap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_attribute.attributemap
	 * @param attributeMap  the value for uuc_attribute.attributemap
	 * @mbggenerated
	 */
	public void setAttributeMap(String attributeMap) {
		this.attributeMap = attributeMap == null ? null : attributeMap.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uuc_attribute.needed
	 * @return  the value of uuc_attribute.needed
	 * @mbggenerated
	 */
	public Integer getNeeded() {
		return needed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uuc_attribute.needed
	 * @param needed  the value for uuc_attribute.needed
	 * @mbggenerated
	 */
	public void setNeeded(Integer needed) {
		this.needed = needed;
	}
}