package com.sogou.bizwork.cas.application.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class AttributeExample implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public AttributeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAttributeIdIsNull() {
			addCriterion("attributeid is null");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIsNotNull() {
			addCriterion("attributeid is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeIdEqualTo(Integer value) {
			addCriterion("attributeid =", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotEqualTo(Integer value) {
			addCriterion("attributeid <>", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdGreaterThan(Integer value) {
			addCriterion("attributeid >", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("attributeid >=", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLessThan(Integer value) {
			addCriterion("attributeid <", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLessThanOrEqualTo(Integer value) {
			addCriterion("attributeid <=", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIn(List<Integer> values) {
			addCriterion("attributeid in", values, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotIn(List<Integer> values) {
			addCriterion("attributeid not in", values, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdBetween(Integer value1, Integer value2) {
			addCriterion("attributeid between", value1, value2, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("attributeid not between", value1, value2,
					"attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeNameIsNull() {
			addCriterion("attributename is null");
			return (Criteria) this;
		}

		public Criteria andAttributeNameIsNotNull() {
			addCriterion("attributename is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeNameEqualTo(String value) {
			addCriterion("attributename =", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameNotEqualTo(String value) {
			addCriterion("attributename <>", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameGreaterThan(String value) {
			addCriterion("attributename >", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameGreaterThanOrEqualTo(String value) {
			addCriterion("attributename >=", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameLessThan(String value) {
			addCriterion("attributename <", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameLessThanOrEqualTo(String value) {
			addCriterion("attributename <=", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameLike(String value) {
			addCriterion("attributename like", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameNotLike(String value) {
			addCriterion("attributename not like", value, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameIn(List<String> values) {
			addCriterion("attributename in", values, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameNotIn(List<String> values) {
			addCriterion("attributename not in", values, "attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameBetween(String value1, String value2) {
			addCriterion("attributename between", value1, value2,
					"attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeNameNotBetween(String value1, String value2) {
			addCriterion("attributename not between", value1, value2,
					"attributeName");
			return (Criteria) this;
		}

		public Criteria andAttributeValueIsNull() {
			addCriterion("attributevalue is null");
			return (Criteria) this;
		}

		public Criteria andAttributeValueIsNotNull() {
			addCriterion("attributevalue is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeValueEqualTo(String value) {
			addCriterion("attributevalue =", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueNotEqualTo(String value) {
			addCriterion("attributevalue <>", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueGreaterThan(String value) {
			addCriterion("attributevalue >", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueGreaterThanOrEqualTo(String value) {
			addCriterion("attributevalue >=", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueLessThan(String value) {
			addCriterion("attributevalue <", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueLessThanOrEqualTo(String value) {
			addCriterion("attributevalue <=", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueLike(String value) {
			addCriterion("attributevalue like", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueNotLike(String value) {
			addCriterion("attributevalue not like", value, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueIn(List<String> values) {
			addCriterion("attributevalue in", values, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueNotIn(List<String> values) {
			addCriterion("attributevalue not in", values, "attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueBetween(String value1, String value2) {
			addCriterion("attributevalue between", value1, value2,
					"attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeValueNotBetween(String value1, String value2) {
			addCriterion("attributevalue not between", value1, value2,
					"attributeValue");
			return (Criteria) this;
		}

		public Criteria andAttributeMapIsNull() {
			addCriterion("attributemap is null");
			return (Criteria) this;
		}

		public Criteria andAttributeMapIsNotNull() {
			addCriterion("attributemap is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeMapEqualTo(String value) {
			addCriterion("attributemap =", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapNotEqualTo(String value) {
			addCriterion("attributemap <>", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapGreaterThan(String value) {
			addCriterion("attributemap >", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapGreaterThanOrEqualTo(String value) {
			addCriterion("attributemap >=", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapLessThan(String value) {
			addCriterion("attributemap <", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapLessThanOrEqualTo(String value) {
			addCriterion("attributemap <=", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapLike(String value) {
			addCriterion("attributemap like", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapNotLike(String value) {
			addCriterion("attributemap not like", value, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapIn(List<String> values) {
			addCriterion("attributemap in", values, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapNotIn(List<String> values) {
			addCriterion("attributemap not in", values, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapBetween(String value1, String value2) {
			addCriterion("attributemap between", value1, value2, "attributeMap");
			return (Criteria) this;
		}

		public Criteria andAttributeMapNotBetween(String value1, String value2) {
			addCriterion("attributemap not between", value1, value2,
					"attributeMap");
			return (Criteria) this;
		}

		public Criteria andNeededIsNull() {
			addCriterion("needed is null");
			return (Criteria) this;
		}

		public Criteria andNeededIsNotNull() {
			addCriterion("needed is not null");
			return (Criteria) this;
		}

		public Criteria andNeededEqualTo(Integer value) {
			addCriterion("needed =", value, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededNotEqualTo(Integer value) {
			addCriterion("needed <>", value, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededGreaterThan(Integer value) {
			addCriterion("needed >", value, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededGreaterThanOrEqualTo(Integer value) {
			addCriterion("needed >=", value, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededLessThan(Integer value) {
			addCriterion("needed <", value, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededLessThanOrEqualTo(Integer value) {
			addCriterion("needed <=", value, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededIn(List<Integer> values) {
			addCriterion("needed in", values, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededNotIn(List<Integer> values) {
			addCriterion("needed not in", values, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededBetween(Integer value1, Integer value2) {
			addCriterion("needed between", value1, value2, "needed");
			return (Criteria) this;
		}

		public Criteria andNeededNotBetween(Integer value1, Integer value2) {
			addCriterion("needed not between", value1, value2, "needed");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uuc_attribute
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uuc_attribute
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}