package com.sogou.bizwork.cas.application.model;

import java.io.Serializable;
import java.util.Date;

public class LogonLog implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8955779858655334827L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.accountid
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.accountname
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.serviceurl
     *
     * @mbggenerated
     */
    private String serviceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.userip
     *
     * @mbggenerated
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.logontime
     *
     * @mbggenerated
     */
    private Date logonTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logon_log.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.id
     *
     * @return the value of logon_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.id
     *
     * @param id the value for logon_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.accountid
     *
     * @return the value of logon_log.accountid
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.accountid
     *
     * @param accountId the value for logon_log.accountid
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.accountname
     *
     * @return the value of logon_log.accountname
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.accountname
     *
     * @param accountName the value for logon_log.accountname
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.serviceurl
     *
     * @return the value of logon_log.serviceurl
     *
     * @mbggenerated
     */
    public String getServiceUrl() {
        return serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.serviceurl
     *
     * @param serviceUrl the value for logon_log.serviceurl
     *
     * @mbggenerated
     */
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl == null ? null : serviceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.user_type
     *
     * @return the value of logon_log.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.user_type
     *
     * @param userType the value for logon_log.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.userip
     *
     * @return the value of logon_log.userip
     *
     * @mbggenerated
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.userip
     *
     * @param userIp the value for logon_log.userip
     *
     * @mbggenerated
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp == null ? null : userIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.logontime
     *
     * @return the value of logon_log.logontime
     *
     * @mbggenerated
     */
    public Date getLogonTime() {
        return logonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.logontime
     *
     * @param logonTime the value for logon_log.logontime
     *
     * @mbggenerated
     */
    public void setLogonTime(Date logonTime) {
        this.logonTime = logonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.status
     *
     * @return the value of logon_log.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.status
     *
     * @param status the value for logon_log.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logon_log.reason
     *
     * @return the value of logon_log.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logon_log.reason
     *
     * @param reason the value for logon_log.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}