package com.sogou.bizwork.cas.user.model;

import java.sql.Timestamp;
import java.util.Arrays;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
     * @mbggenerated
     */
    private String userName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
     * @mbggenerated
     */
    private String email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.chinesename
     * @mbggenerated
     */
    private String chineseName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.groupname
     * @mbggenerated
     */
    private String groupName;
    // 新加字段
    private Integer groupId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.birthday
     * @mbggenerated
     */
    private String birthday;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.telephone
     * @mbggenerated
     */
    private String telephone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
     * @mbggenerated
     */
    private String mobile;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
     * @mbggenerated
     */
    private Boolean role;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.state
     * @mbggenerated
     */
    private Boolean state;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.level
     * @mbggenerated
     */
    private String level;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.job
     * @mbggenerated
     */
    private String job;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.photo
     * @mbggenerated
     */
    private byte[] photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated
	 */
	private Integer employeeId;
	private Timestamp lastLoginTime;

	private Timestamp updateUserTime;
	private String ipAddress;
	
	public Timestamp getUpdateUserTime() {
		return updateUserTime;
	}

	public void setUpdateUserTime(Timestamp updateUserTime) {
		this.updateUserTime = updateUserTime;
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	/**
||||||| .r408
    /**
=======
    public Timestamp getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(Timestamp lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
>>>>>>> .r410
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
     * @return  the value of user.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
     * @param id  the value for user.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
     * @return  the value of user.username
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }
    public Integer getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
     * @param userName  the value for user.username
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
     * @return  the value of user.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
     * @param email  the value for user.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.chinesename
     * @return  the value of user.chinesename
     * @mbggenerated
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.chinesename
     * @param chineseName  the value for user.chinesename
     * @mbggenerated
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName == null ? null : chineseName.trim();
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.groupname
     * @return  the value of user.groupname
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.groupname
     * @param groupName  the value for user.groupname
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.birthday
     * @return  the value of user.birthday
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.birthday
     * @param birthday  the value for user.birthday
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.telephone
     * @return  the value of user.telephone
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.telephone
     * @param telephone  the value for user.telephone
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
     * @return  the value of user.mobile
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
     * @param mobile  the value for user.mobile
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
     * @return  the value of user.role
     * @mbggenerated
     */
    public Boolean getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
     * @param role  the value for user.role
     * @mbggenerated
     */
    public void setRole(Boolean role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.state
     * @return  the value of user.state
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.state
     * @param state  the value for user.state
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.level
     * @return  the value of user.level
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.level
     * @param level  the value for user.level
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.job
     * @return  the value of user.job
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.job
     * @param job  the value for user.job
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.photo
     * @return  the value of user.photo
     * @mbggenerated
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.photo
     * @param photo  the value for user.photo
     * @mbggenerated
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", userName=" + userName + ", email=" + email + ", chineseName=" + chineseName
                + ", groupName=" + groupName + ", groupId=" + groupId + ", birthday=" + birthday + ", telephone="
                + telephone + ", mobile=" + mobile + ", role=" + role + ", state=" + state + ", level=" + level
                + ", job=" + job + ", photo=" + Arrays.toString(photo) + "]";
    }


    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}