package com.sogou.bizwork.cas.application.dao;

import com.sogou.bizwork.cas.application.model.Application;
import com.sogou.bizwork.cas.application.model.ApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int countByExample(ApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int deleteByExample(ApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int insert(Application record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int insertSelective(Application record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	List<Application> selectByExample(ApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	Application selectByPrimaryKey(Integer appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Application record,
			@Param("example") ApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Application record,
			@Param("example") ApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Application record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uuc_application
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Application record);
}