package com.sogou.bizwork.cas.application.dao;

import com.sogou.bizwork.cas.application.model.LogonLog;
import com.sogou.bizwork.cas.application.model.LogonLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogonLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int countByExample(LogonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int deleteByExample(LogonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int insert(LogonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int insertSelective(LogonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    List<LogonLog> selectByExample(LogonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    LogonLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogonLog record, @Param("example") LogonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogonLog record, @Param("example") LogonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logon_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogonLog record);
}